# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      minor-maven-dependencies:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      major-maven-dependencies:
        patterns:
          - "*"
        update-types:
          - "major"
    ignore:
      - dependency-name: "com.datastax.cassandra:cassandra-driver-core"
        # Only upgrade cassandra driver to most recent version fitting our productive cassandras (currently 3.x.x)
        versions: [ "[4.0.0,)" ]
      - dependency-name: "com.fasterxml.jackson:jackson-bom"
        versions: [ "2.20.0-rc1" ]
      - dependency-name: "com.google.code.gson:gson"
        # There are breaking changes in 2.11.0, so don't try to update this until we decided how to solve this
        versions: [ "[2.11.0,2.13.1]" ]
      - dependency-name: "jakarta.inject:jakarta.inject-api"
        versions: [ "2.0.1.MR" ]
      - dependency-name: "org.jooq:jooq"
        # Dependency not brought to 3.20 or higher since java 21 is needed for open source variant
        versions: [ "[3.20.0,)" ]
