== About Mizool
_TODO_


== How to make a release and deploy it to Central

Mizool uses the http://nvie.com/posts/a-successful-git-branching-model/[Gitflow branching model] by
http://nvie.com/about/[Vincent Driessen]. For now the commits and merges have to be performed manually, the builds are
performed by https://travis-ci.org/[Travis].

=== Starting the release process

. Set the versions in environment variables.
+
----
set CURRENT_RELEASE_VERSION=
set NEXT_DEVELOP_SNAPSHOT=
----
+
. Check out the current `develop` branch.
+
----
git fetch "origin"
git checkout -B develop remotes/origin/develop --
----
+
. Replace all `-SNAPSHOT` dependencies with the corresponding release versions if necessary and commit the change.
+
----
git commit -a -m "[gitflow] Prepare release"
----
+
. Create `release` branch.
+
----
git branch release/%CURRENT_RELEASE_VERSION%
----
+
. Update the versions on `develop` to the next `-SNAPSHOT` version.
+
----
call mvn versions:set -DgenerateBackupPoms=false -DnewVersion=%NEXT_DEVELOP_SNAPSHOT%
git commit -a -m "[gitflow] updating poms for %NEXT_DEVELOP_SNAPSHOT% development"
----
+
. Push the changes atomically.
+
----
git push --atomic origin develop release/%CURRENT_RELEASE_VERSION%
----
+
. Wait for the https://travis-ci.org/[Travis] build for the `release/` branch to succeed, test and stabilize as needed.

=== Finishing the release

. Checkout the `release` branch.
+
----
git fetch "origin"
git checkout -B release/%CURRENT_RELEASE_VERSION% remotes/origin/release/%CURRENT_RELEASE_VERSION% --
----
+
. Verify that no new `-SNAPSHOT` dependencies were added during stabilization. Replace them with release versions if
necessary.
. Replace the `-SNAPSHOT` versions on the `release` branch with the release versions.
+
----
call mvn versions:set -DgenerateBackupPoms=false -DnewVersion=%CURRENT_RELEASE_VERSION%
git commit -a -m "[gitflow] updating poms for branch 'release/%CURRENT_RELEASE_VERSION%' with non-snapshot versions"
----
+
. Merge the `release` branch to `master` and create a tag.
+
----
git checkout -B master remotes/origin/master --
git merge --no-ff -m "[gitflow] merging 'release/%CURRENT_RELEASE_VERSION%' into 'master'" release/%CURRENT_RELEASE_VERSION%
git tag %CURRENT_RELEASE_VERSION%
----
+
. Update the `-SNAPSHOT` versions on `develop` with the release version to avoid merge conflicts, merge `master` to
`develop` and set the versions on `develop` back to the next `-SNAPSHOT` version.
+
----
git checkout -B develop remotes/origin/develop --
call mvn versions:set -DgenerateBackupPoms=false -DnewVersion=%CURRENT_RELEASE_VERSION%
git commit -a -m "[gitflow] updating develop poms to master versions to avoid merge conflicts"
git merge --no-ff -m "[gitflow] merging 'master' into 'develop'" master
call mvn versions:set -DgenerateBackupPoms=false -DnewVersion=%NEXT_DEVELOP_SNAPSHOT%
git commit -a -m "[gitflow] updating develop poms back to pre merge state"
----
+
. Push the changes atomically. https://travis-ci.org/[Travis] will now start building the release on `master`.
+
----
git push --atomic origin master develop refs/tags/%CURRENT_RELEASE_VERSION%
----
+
. Delete the `release` branch.
+
----
git push origin --delete release/%CURRENT_RELEASE_VERSION%
git branch -d release/%CURRENT_RELEASE_VERSION%
----
+
. The artifact should appear on Central within an hour or so. If you are impatient and want to check whether the release
made it to Central, be aware that the https://search.maven.org/[search engine] seems to have a larger lag. Instead,
check the https://repo.maven.apache.org/maven2/com/github/mizool/mizool/VERSION/[URL of the release on central].

=== Troubleshooting

If the Sonatype staging plugin reports errors, you can log into https://oss.sonatype.org/ with your OSSRH credentials to
investigate the situation. Navigate to "Staging Repositories" and search for a repo called `comgithubmizool-XXXX`.

== Deployment setup details

Mizool is deployed to the Central repository via OSSRH using Travis CI. The setup is based on an
http://www.debonair.io/post/maven-cd/[article on debonair.io] with the following deviations:

* The folder `cd` is called `ci-resources` to make its purpose more obvious.
* We used a Windows machine (except for encryption, see below)
** The shell scripts in `ci-resources` were added with `git add --chmod=+x *.sh` to make them executable on Linux.
* The profile `build-extras` does not include `maven-sources-plugin` as we always run it anyway. Also, the profile is
  not active by default as it is activated explicitly in the deployment command.
* Environment variables
** When preparing the encrypted variables `OSSRH_JIRA_USERNAME` and `OSSRH_JIRA_PASSWORD`, we did *not* use actual JIRA
   credentials. Instead, we used tokens. To fetch those, use OSSRH JIRA credentials to log in to
   https://oss.sonatype.org/[OSSRH Nexus], view the user profile and select `User Token > Access`.
** When `GPG_PASSPHRASE` included spaces, setting it via the Travis CLI or the Travis website resulted in the value being
   truncated at the position of the first space character. We changed to a space-free passphrase.
* File encryption
** On Windows, encrypting files using either the Travis CLI or direct openssl invocations resulted in garbled
   files that could not be decrypted. So the encryption was performed on a Linux box. As installation of the Travis CLI
   failed, pure openssl was used instead.
*** The password used is stored in an environment variable `CODESIGNING_AES_PASSWORD` in the Travis settings.
*** The decryption command in `before-deploy` was adapted accordingly.
* For the GPG import command, we specify the `--batch` and `--quiet` options to skip a warning regarding a preference
  for an unsupported cipher.
* In the article, there are several different maven invocations, which we combined into one for the following reasons:
** Multiple maven invocations bring a slight overhead that must be justified. Furthermore, it makes the build logs
   significantly more verbose.
** The idea of the Travis `install` phase seems to be to install any necessary prerequisites before starting the real
   build. This is not a good fit for Maven as it downloads each plugin during the respective phase of its build,
   so there is no real "install dependencies without compiling" command.
** Travis updates its cache after `script`, but before the `after_success` phase, so the plugins used by the maven
   invocation during `after_success` were downloaded on each build.
** Errors during deployment to the Central repository should break the build, so the deployment must happen in the
   `script` phase.
* The script names and the phases used for invoking them were changed to reflect the decision above.
* The maven invocation for non-`master` builds was changed from `install` to `package`. The former would put the
  build results into the local repository and hence the cache, which offers no advantage.
* As the Travis docker images https://github.com/travis-ci/travis-ci/issues/2727[do not configure any Maven toolchains],
  a suitable configuration file is installed by `before-build.sh`.