name: Build

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # TODO remove printenv
      - name: printenv
        run: printenv

      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare directories
        run: mkdir -p /home/runner/work/_temp/_github_home/talos-m2-repository

      - name: Maven Repo Cache
        uses: actions/cache@v2
        with:
          path: /home/runner/work/_temp/_github_home/talos-m2-repository
          # TODO finalize name and/or make configurable
          key: talos-maven-repo-dummy3

      - name: Build
        uses: docker://incub8softwarelabs/pipelines-build-environment:feature_CCCP-37-add-github-support
        env:
          # Talos-specific variables
          TALOS_SIGNING_ENABLED: ${{ secrets.TALOS_SIGNING_ENABLED }}
          TALOS_SIGNING_KEY: ${{ secrets.TALOS_SIGNING_KEY }}
          TALOS_SIGNING_PROFILE: ${{ secrets.TALOS_SIGNING_PROFILE }}
          TALOS_SONAR_ENABLED: ${{ secrets.TALOS_SONAR_ENABLED }}
          TALOS_SONAR_HOST: ${{ secrets.TALOS_SONAR_HOST }}
          TALOS_SONAR_ORGANIZATION: ${{ secrets.TALOS_SONAR_ORGANIZATION }}
          TALOS_SONAR_LOGIN: ${{ secrets.TALOS_SONAR_LOGIN }}

          # Token to use when SonarScanner invokes Github APIs
          # https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
